spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    #schema: classpath:import.sql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      ## 为了获得最佳性能, 建议不要设置minimumIdle值, 而是允许HikariCP充当固定大小的连接池(默认值与maximumPoolSize相同)
      #minimum-idle: 20
      maximum-pool-size: 20

app:
  jwt:
    private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCfVP1oq9mTSQPdMVf6-rtFBN1Zc6eawg_bDnQMwFEUUCwrOCTaX-xiX-qHw0pr7UTLqN-s4gb_6ySKHqpr2Zy617FcaGSrXk9qZhVc1aZ1cqvv3eed0yeGx4hPw4n4Iy6FbYmYVejdWY122TqIAR7C6WEBJX0Y6fpk41IPS98g5IN6wD56xw9wOt_DgjEIH0G5ASmu-E-0rH1qD-8fa-C1QXFByvZmE3_4nmKNZu77aYRhR0PQWyu8AvqFuQeFUh8nwUYx9T5rnWJ7xdNqGMn0r303pNmr0InHOgG6cBMqkNWqCcganS8VdmOSxP-JsXm5sKmzZtqHlPLEJB0ebSCvAgMBAAECggEAML4eW_QetpkirntW7_febGnlkWT5RDXUBe6w_-mhpDY2nO4rEAdCWIIBTJEo5kWKw0chTlFDVO1Jm1twRVgoQ1yS7LMfAPH0F5etN15A8zMmeFYJclXThL7r64LlZVzV8YmmC01U1Mp9pXslFdBJ6dTdkS03zPRfXpfQVc-fLf9bm74MfPkrtDoOlnUTU4ci-uCLzdxN6ifEOWNnkpIhx01L2ewp0bwq6pmOVViWDfB4Z2XgVYciH-pnxQ0-8xaitU576_8tDN8d4rImU7EJ53sTlmzKYWcA7kvVCU-nOx4ED1Xsn99ijiAbpYSyGbeaPyEJFA-vOMBZDqLptQZZcQKBgQD9Vhm4Qd5JKmv4Yk4Lv870bfiSyc9WWV6s-PY3bbk7rSl9XRj1mJzrF5pysPqq_EtY4WH2CbeS9_OTyg6b5H1jZNzkOmckx-qJEckurT9bhuJalro2HvVndzwTJiYsh1mcrgKkWjr5xBHiBDixPD8Oj3qYJjhVTjNg-Nb-48MvlwKBgQChAdwwMv0rll59i8dlsWTxRM734ZIWyF2askBOHCRBmJifAQ3w8fTUjz0NYjBjUwOu53WOMF7uV1cto2eqYdkkKLhdsjT5Ujtp7sf1oSl_Ept9WApo8Hj9SskKKGjlfcZRwFWXViXVEtfMOGSmrqv3ufHumi7s5osOuTVWndm6qQKBgC_7p-FzcGPRSiQAkqG9EbjQP32mBcRoJvuCKDh1atk3wh0BjiGuZ0JL9S_1_3R1VtwdzE0qp_-JQTRj2AKE847o4sHDohegWfbeTImvvMlcMfFQjTKFCJwxREqoNiDG_h0kBFIW2QbHsU9q10YSkCr02BaLXq4hoq-iUi5y-1w_AoGAULa0AV2uWSl6mQl3nl09s03BS7bDG7S6aBCv9_hXnKK48A0BRiali-F6w7jTdRdqo0XZQryw-l7Cj1h5YYrH5j6bniz2LX6x1jsj9tkiClfzpvR5032pyaCyA-uaGmHhB56ZydIgCR73G6OxoXWzM-79f5W_rHcuguUJ_jAHtHECgYA-rZyQ972K0mCrQQxCVWTWmYLTk-GgwWyMau8LKpCjvjH3OpN9YKKImZbzJ4M2grctpIeL7LftpDkJFulBU7ADAh8zU4WN52XIejZC1G0NzZghlf-818HPFKRBWmWAibgFJPGqTJ3qI5-BTaRGop2dgsgXTZux_WyDtOAiiSF_VQ==
