# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8081

spring:
  application:
    name: cloud-auth

management:
  security:
    enabled: false

# Hystrix\u670D\u52A1\u7194\u65AD\u5904\u7406(\u53EA\u4F5C\u7528\u5728\u670D\u52A1\u8C03\u7528\u7684\u4E00\u7AEF)
feign:
  hystrix:
    enabled: true

app:
  auth:
    private-key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBALaR156vt0cF7m7zXT1MAxzkujT34Lk6pPuz7NLWPOzaEKJYwE5aQdtNqRpnYJFJ6mO5d40NsX4U8BEGdCYCRwRLnY5qcOc8tXVZJRrtciSfDX8rdQz5HqsXqYSatOGWtO9vpW9X1ymUbZJqJoNIGSF-e7VTLu6vsqYAm2FsEmZvAgMBAAECgYBxU7x9c2OYQbVMx-JDz3BLOivf_1JOiHmrCHfkNDpjZ8VVkTPmLx6cK-vhSPRnm3NUbeco9qwLsKGIX_IvOdCsaw0ao93_eSvhVz5BKMAIE7EqEciSELgSnD0AGPCistnM8wTP4xVlM7OzIC6thgsLbzqKEJ6H2g3ywFrtVaKzeQJBAO_tAeGd-pIkTI0z7fhmaV-xCqZM59MJBbkdjhgoJVn1pvm8nORYmbtbb-1jLMF-z4YAIUBrnoA8BC1I2M_oPgsCQQDCzR09MtT1whu7XOnH5k11KEa295PmvvqEH7YCK7Oc7jQy3eX0EYLVa-29xp5RCM0OrYXk_CKDsDgnXzWcIgutAkBytSiyGpqi5lHnLI24thXpFzbVPW2Umvquf2_hIsiA0w6q1b9Y-Pc--T9xCnpqZFuJYGSFbS6RdqA0mmB2Pj3zAkAFt0ULXal4CJkNt104u148eNESX1Ncqu_o3pFVoPilOywW7gHoVnczUfZo4iIVGKADtT2_iVJt8MbFCPsmuK0FAkAreClvH_wlic5VV5aWewtU3QiSjdaTkPurJvUq4q8MRWWGqJDW8EW-8Yh4cJdceaMrcSJjgdv-fE_H3SBeTZFV
