# http://127.0.0.1:8000/app-default.yml
# config服务端修改配置信息后, config客户端需要手动refresh(http://ip:port/refresh)才能生效
zuul:
  prefix: /rest
  routes:
    cloud-sys: /sys/**
    cloud-auth: /auth/**

app:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn1T9aKvZk0kD3TFX-vq7RQTdWXOnmsIP2w50DMBRFFAsKzgk2l_sYl_qh8NKa-1Ey6jfrOIG_-skih6qa9mcutexXGhkq15PamYVXNWmdXKr793nndMnhseIT8OJ-CMuhW2JmFXo3VmNdtk6iAEewulhASV9GOn6ZONSD0vfIOSDesA-escPcDrfw4IxCB9BuQEprvhPtKx9ag_vH2vgtUFxQcr2ZhN_-J5ijWbu-2mEYUdD0FsrvAL6hbkHhVIfJ8FGMfU-a51ie8XTahjJ9K99N6TZq9CJxzoBunATKpDVqgnIGp0vFXZjksT_ibF5ubCps2bah5TyxCQdHm0grwIDAQAB
    validity-in-seconds: 1800
    cookie-path: /
    cookie-name: accessToken
    cookie-max-age: -1             # 若设置的值不大于0则关闭浏览器失效
    use-http-only-cookie: true     # 若设置为true则通过JS脚本将无法读取到Cookie信息(防止XSS跨站脚本攻击)
    use-secure-cookie: false       # 若设置为true则只能在Https连接中被浏览器传递到服务端
  auth:
    anonUrls:
      - /rest/sys/**
      - /rest/auth/**
    userUrls:
      - /rest/auth/account/**
    authcUrls:
      - /rest/sys/user/**