# ===================================================================
# http://127.0.0.1:8000/application-default.yml
#
# config服务端修改配置信息后, config客户端需要手动refresh(http://ip:port/refresh)才能生效
# ===================================================================

app:
  jwt:
    access-token-expires: 1800
    refresh-token-expires: 2592000
    enable-cookie: true
    cookie:
      path: /
      name: accessToken
      domain:          # 顶级域名(domain.com)
      max-age: -1      # 若设置的值不大于0则关闭浏览器失效
      http-only: true  # 若设置为true则通过JS脚本将无法读取到Cookie信息(防止XSS跨站脚本攻击)
      secure: false    # 若设置为true则只能在Https连接中被浏览器传递到服务端
  acl:
    anonUrls:
      - /**/v2/api-docs/**
      - /**/swagger-resources/**
      - /**/webjars/springfox-swagger-ui/**
      - /**/swagger-ui.html
      - /auth/login/**
      - /auth/register/**
    userUrls:
      - /auth/logout/**
    authUrls:
      - /sys/**
      - /auth/**