# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 9000

spring:
  application:
    name: cloud-gateway

management:
  security:
    enabled: false #全局关闭Actuator安全认证
#endpoints:
#  env:
#    sensitive: false #细粒度的开放Actuator Endpoints

#ribbon:
#  eureka:
#    enabled: true

# https://projects.spring.io/spring-cloud/spring-cloud.html
zuul:
  #host:
  #  max-total-connections: 1000
  #  max-per-route-connections: 100
  #semaphore:
  #  max-semaphores: 500
  add-host-header: true
  sensitiveHeaders: #Cookie, Set-Cookie, Authorization
