server:
  port: 9000

spring:
  application:
    name: cloud-gateway
  profiles:
    active: @profile.active@
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR