# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# http://127.0.0.1/rest/cms/swagger-ui.html
spring:
  profiles:
    include: swagger

# RibbonTimeout=(ribbonReadTimeout+ribbonConnectTimeout)*(maxAutoRetries+1)*(maxAutoRetriesNextServer+1)
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

# https://github.com/Netflix/Hystrix/wiki/Configuration
# Feign\u548CRibbon\u5728\u6574\u5408\u4E86Hystrix\u540E\u53EF\u80FD\u4F1A\u51FA\u73B0\u9996\u6B21\u8C03\u7528\u5931\u8D25\u7684\u95EE\u9898, \u9020\u6210\u8BE5\u95EE\u9898\u7684\u539F\u56E0\u662FHystrix\u9ED8\u8BA4\u7684\u8D85\u65F6\u65F6\u95F4\u662F1\u79D2,
# \u5982\u679C\u8D85\u8FC7\u8FD9\u4E2A\u65F6\u95F4\u5C1A\u672A\u54CD\u5E94, \u5C06\u4F1A\u8FDB\u5165fallback\u4EE3\u7801, \u800C\u9996\u6B21\u8BF7\u6C42\u5F80\u5F80\u4F1A\u6BD4\u8F83\u6162(\u56E0\u4E3ASpring\u7684\u61D2\u52A0\u8F7D\u673A\u5236, \u8981\u5B9E\u4F8B\u5316\u4E00\u4E9B\u7C7B), \u8FD9\u4E2A\u54CD\u5E94\u65F6\u95F4\u53EF\u80FD\u5C31\u8D85\u8FC71\u79D2.
# \u89E3\u51B3\u529E\u6CD5:
# - \u7981\u7528Hystrix\u7684\u8D85\u65F6\u65F6\u95F4(hystrix.command.default.execution.timeout.enabled=false)
# - \u5EF6\u957FHystrix\u7684\u8D85\u65F6\u65F6\u95F4(hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=10000)
# - \u7981\u7528Feign\u7684Hystrix(\u4E0D\u63A8\u8350\u4F7F\u7528)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
