# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8082

spring:
  application:
    name: cloud-mail
  profiles:
    active: @profile.active@
  mail:
    host: smtp.qq.com
    username: lu774374302@qq.com
    password: fbxthbgaymolbegf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  messages:
      basename: i18n/messages

management:
  security:
    enabled: false

app:
  mail:
    from: ${spring.mail.username}
    base-url: http://127.0.0.1