# ===================================================================
# Mybatis properties.
# Full reference is available at:
# {@link org.mybatis.spring.boot.autoconfigure.MybatisProperties}
# ===================================================================
mybatis:
  #type-aliases-package: com.gavin.cloud.sys.pojo
  #type-aliases-super-type: com.gavin.cloud.common.base.pojo.AbstractModel
  #type-handlers-package: com.gavin.cloud.sys.core.mapper
  #executor-type: BATCH
  configuration:
    # 开启自动驼峰命名规则
    map-underscore-to-camel-case: true
    # 开启延迟加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    # 禁用二级缓存
    cache-enabled: false
    #database-id: mysql

sftp:
  username: ftpuser
  password: ftpuser
  host: 192.168.8.99
  port: 22
  timeout: 30000
  basePath: /home/ftpuser/www/images

oss:
  baseURL: http://192.168.8.99/images
