spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    #schema: classpath:import.sql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      ## 为了获得最佳性能, 建议不要设置minimumIdle值, 而是允许HikariCP充当固定大小的连接池(默认值与maximumPoolSize相同)
      #minimum-idle: 20
      maximum-pool-size: 20
