# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 7000

spring:
  application:
    name: cloud-trace

logging:
  file: target/${spring.application.name}.log

management:
  security:
    enabled: false

# https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.2.6.RELEASE/
