# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  address: 127.0.0.1
  port: ${random.int[8088,8089]}

spring:
  application:
    name: cloud-webflux
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/webflux
