# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  address: 127.0.0.1
  port: ${random.int[8080,8090]}

spring:
  application:
    name: cloud-test
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password: #secret#
    redisson:
      config: classpath:redisson.yml

management:
  security:
    enabled: false

app:
  zookeeper:
    address: 127.0.0.1:2181
    root: /election
  contact-name: lugavin
  contact-url: https://github.com/lugavin
