# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8081

spring:
  application:
    name: cloud-auth

#ribbon:
#  eureka:
#    enabled: true  # 是否在Ribbon中使用Eureka
#  eager-load:
#    enabled: true  # 启动时就创建Ribbon上下文(避免首次访问超时)
#    clients: cloud-sys

feign:
  hystrix:
    enabled: true
