# ===================================================================
# Spring Boot configuration for the "prod" profile.
# This configuration overrides the application.yml file.
# ===================================================================

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password: #secret#

logging:
  level:
    com.gavin.cloud: INFO

# http://host:port/swagger-ui.html
springdoc:
  api-docs:
    enabled: false
