# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    include: swagger #http://127.0.0.1:8080/swagger-ui.html
  jackson:
    serialization:
      indent_output: true
  output:
    ansi:
      enabled: ALWAYS
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password: #secret#

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.gavin.cloud: DEBUG

app:
  swagger:
    title: Cloud App RESTful API
    description: Cloud App API documentation
    termsOfServiceUrl: https://lugavin.github.io
    contactName: lugavin
    contactUrl: https://github.com/lugavin
    contactEmail: lugavin@outlook.com
    basePackage: com.gavin.cloud
    default-include-pattern: /**
    protocols: http, https
    version: 0.1.0