# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: dev #spring.profiles.active#
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    serialization:
      write_dates_as_timestamps: false

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR

app:
  swagger:
    title: Cloud App RESTful API
    description: Cloud App API documentation
    termsOfServiceUrl: https://lugavin.github.io
    contactName: lugavin
    contactUrl: https://github.com/lugavin
    contactEmail: lugavin@outlook.com
    basePackage: com.gavin.cloud
    default-include-pattern: /**
    protocols: http, https
    version: 0.1.0
