# ===================================================================
# Spring Boot configuration for the "prod" profile.
# This configuration overrides the application.yml file.
# ===================================================================

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password: #secret#

logging:
  level:
    com.gavin.cloud: INFO

springfox:
  documentation:
    enabled: false