# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.
# ===================================================================

spring:
  jackson:
    serialization:
      indent_output: true
  output:
    ansi:
      enabled: ALWAYS
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password: #secret#

logging:
  level:
    com.gavin.cloud: DEBUG
