# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev #spring.profiles.active#
    session:
        #store-type: none
        store-type: redis # https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-redis.html
    messages:
        basename: i18n/messages
    jackson:
        time-zone: Asia/Shanghai
        date-format: yyyy-MM-dd HH:mm:ss
        default-property-inclusion: NON_NULL
        serialization:
            write_dates_as_timestamps: false

info:
    project:
        version: 0.1.0 #project.version#

ribbon:
    eureka:
        enabled: true
app:
  cookie:
    cookie-name: accessToken
    cookie-path: /
    domain-name:
    use-http-only-cookie: true
    use-secure-cookie: false
    cookie-max-age: -1
    use-base64-encoding: true
