spring:
  cloud:
    config:
      server:
        git:
          #uri: file:///${user.dir}/${spring.application.name}/src/main/resources/repo
          uri: https://github.com/lugavin/cloud
          default-label: master
          search-paths: config
          username: lugavin
          password: changeit