# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8000

spring:
  application:
    name: cloud-config
  # To use the native profile just launch the Config Server with "spring.profiles.active=native".
  profiles:
    active: native
  cloud:
    config:
      server:
        # File System Backend
        native:
          search-locations: classpath:/repo
        # Git Backend
        #git:
        #  uri: file:///${user.dir}/${spring.application.name}/src/main/resources/repo

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR