spring:
  # To use the native profile just launch the Config Server with "spring.profiles.active=native".
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/repo